routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', '\App\Http\Controllers\Welcome');

Route::get('/admin', '\App\Http\Controllers\ShowAdmin');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::post('/token', [App\Http\Controllers\HomeController::class, 'storeKey'])->name('user.token');

Route::resource('/cities', App\Http\Controllers\CitiesController::class);
Route::get('/admin/cities', [App\Http\Controllers\CitiesController::class, 'admin'])->name('cities.admin');

Route::resource('/users', App\Http\Controllers\UsersController::class);

Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'api_key'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Eloquent ORM relationship to cities
     */
    public function cities(){
        return $this->hasMany(City::class);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\City;
use App\Models\User;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Hash;
use Illuminate\View\View;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View|void
     * @throws AuthorizationException
     */
    public function index()
    {
        $users = User::orderBy('id', 'desc')->paginate(30);
        if (Gate::allows('admin-actions')) return view('users.list', compact('users'));
        else return abort('403', 'You are not authorized for this action.');
    }

    /**
     * Function to assign values on edit /create
     * @param Request $request
     * @param User $user
     * @return void
     */
    public function assignValues(Request $request, User $user)
    {
        $request->validate([
            'name' => 'required|string|max:128',
            'email' => 'required|string|email|unique:users',
            'password' => 'required|string',
            'type' => 'integer|min:0|max:1',
        ]);

        $user->name = $request->get('name');
        if ($request->get('type')) {
            $user->type = $request->get('type');
        }
        $user->email = $request->get('email');
        $user->password = Hash::make($request->get('password'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View|void
     */
    public function create()
    {
        if (Gate::allows('admin-actions')) return view('users.create');
        else return abort('403', 'You are not authorized for this action.');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse|Redirector|void
     */
    public function store(Request $request)
    {
        if (Gate::allows('admin-actions')){
        $user = new User;
        $this->assignValues($request, $user);
        $user->save();
        return redirect('/users')->with('success', 'Successfully added a user');}
        else return abort('403', 'You are not authorized for this action.');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Factory|View|void
     * @throws AuthorizationException
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        $this->authorize('update', $user);
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Factory|View|void
     * @throws AuthorizationException
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $this->authorize('update', $user);
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return RedirectResponse|Redirector|void
     * @throws AuthorizationException
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $this->authorize('update', $user);
        $this->assignValues($request, $user);
        $user->save();
        return redirect('/users')->with('success', 'You have updated a user.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return RedirectResponse|Redirector|void
     * @throws \Exception
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $this->authorize('update', $user);
        $cities = City::where('user_id', $user->id)->get();
        foreach ($cities as $city) {
            $city->delete();
        }
        $user->delete();
        return redirect('/users')->with('alert', 'You have deleted a user.');
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')
@section('title', 'Create User')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card bg-transparent border-0">
                    <div class="card-header bg-transparent border-0">{{ __('Create User') }}</div>

                    <div class="card-body bg-transparent border-0">
                        <form method="POST" action="{{ route('users.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control @error('name') is-invalid @enderror" name="name"
                                           value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email"
                                       class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email"
                                           class="form-control @error('email') is-invalid @enderror" name="email"
                                           value="{{ old('email') }}" required autocomplete="email">

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password"
                                           class="form-control @error('password') is-invalid @enderror" name="password"
                                           required autocomplete="password">

                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="type"
                                       class="col-md-4 col-form-label text-md-right">{{ __('User Type') }}</label>

                                <div class="col-md-6">
                                    <select id="type"
                                            class="form-control selectpicker @error('type') is-invalid @enderror" name="type"
                                            required autocomplete="new-password">
                                        <option disabled selected value="">
                                            Select user role here
                                        </option>
                                        <option value="0">
                                          Member
                                        </option>
                                        <option value="1">
                                            Administrator
                                        </option>
                                    </select>
                                    @error('type')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Create User') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit User '.$user->name)
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card bg-transparent border-0">
                    <div class="card-header bg-transparent border-0">{{ __('Edit User') }}</div>

                    <div class="card-body bg-transparent border-0">
                        <form method="POST" action="{{ route('users.update', $user->id) }}">
                            @csrf
                            @method('patch')

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control @error('name') is-invalid @enderror" name="name"
                                           value="@if(old('name')){{old('name')}}@else{{$user->name}}@endif"  autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email"
                                       class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email"
                                           class="form-control @error('email') is-invalid @enderror" name="email"
                                           value="@if(old('email')){{old('email')}}@else{{$user->email}}@endif" required autocomplete="email">

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password"
                                           class="form-control @error('password') is-invalid @enderror" name="password"
                                           required autocomplete="password">

                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="type"
                                       class="col-md-4 col-form-label text-md-right">{{ __('User Type') }}</label>

                                <div class="col-md-6">
                                    <select id="type"
                                            class="form-control selectpicker @error('type') is-invalid @enderror" name="type"
                                            required>
                                        <option disabled value="">
                                            Select user role here
                                        </option>
                                        <option @if($user->type==0) selected @endif value="0">
                                            Member
                                        </option>
                                        <option @if($user->type==1) selected @endif value="1">
                                            Administrator
                                        </option>
                                    </select>
                                    @error('type')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Edit User') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/list.blade.php
@extends('layouts.app')
@section('title', 'Users list')
@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card bg-transparent border-0">
                    <div class="card-header bg-transparent border-0">{{ __('Users list') }}</div>

                    <div class="card-body bg-transparent border-0">
                        <table class="table table-striped text-light">
                            <thead>
                            <tr>
                                <th scope="col">
                                    Type
                                </th>
                                <th scope="col">
                                    Email
                                </th>
                                <th>
                                    API_Key
                                </th>
                                <th scope="col">
                                    Actions (View, Edit, Delete)
                                </th>
                            </tr>
                            <tr>
                                <th colspan="4">{{$users->links()}} <a href="{{url('/users/create')}}">Create New
                                        User</a></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <th>@if($user->type==0) Registered user @else Administrator @endif</th>
                                    <td>
                                        {{$user->email}}
                                    </td>
                                    <td>
                                        @isset($user->api_key) {{$user->api_key}} @else N/A @endif
                                    </td>
                                    <td class="text-center d-inline-flex mx-auto vertical-center"
                                        style="margin-bottom:1px;position:relative;bottom:1px">
                                        <a style="width:60px;height:auto;" class="btn btn-success  my-2 py-2 mx-1"
                                           href="{{url('/users/' . $user->id)}}"><i class="fas fa-eye"></i></a>
                                        <a style="width:60px;height:auto;" class="btn btn-warning  my-2 py-2 mx-1"
                                           href="{{url('/users/' . $user->id.'/edit')}}"><i class="fas fa-edit"></i></a>
                                        <form action="{{route('users.destroy',$user->id) }}" method="POST">
                                            @method('DELETE')
                                            @csrf
                                            <button data-toggle="confirmation" style="width:60px;height:auto;"
                                                    class="btn btn-danger mx-auto my-2 py-2"><i
                                                    class="fas fa-times"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')
@section('title', 'Show user')
@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card bg-transparent border-0">
                    <div class="card-header bg-transparent border-0"><h2>{{ __('User') }}</h2></div>
                    <div class="card-body bg-transparent border-0">
                        <table class="table table-striped">
                            <tbody>
                            <tr>
                                <th scope="row">{{ucfirst('name')}} </th> <td>{{$user->name}}</td>
                            </tr>
                            <tr>
                                <th scope="row">{{ucfirst('email')}} </th> <td>{{$user->email}}</td>
                            </tr>
                            @isset($user->api_key)
                            <tr>
                                <th scope="row">{{ucfirst('api key')}} </th> <td>{{$user->api_key}}</td>
                            </tr>
                            @endisset
                            @isset($user->created_at)
                            <tr>
                                <th scope="row">{{ucfirst('User registered on')}} </th> <td>{{$user->created_at}}</td>
                            </tr>
                            @endisset
                            @isset($user->updated_at)
                                <tr>
                                    <th scope="row">{{ucfirst('User last updated on')}} </th> <td>{{$user->updated_at}}</td>
                                </tr>
                            @endisset
                            <tr>
                                <th scope="row">User Type </th> <td>@if($user->type==0) Member @else Administrator @endif </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection