routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', '\App\Http\Controllers\Welcome');

Route::get('/admin', '\App\Http\Controllers\ShowAdmin');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::post('/token', [App\Http\Controllers\HomeController::class, 'storeKey'])->name('user.token');

Route::resource('/cities', App\Http\Controllers\CitiesController::class);
Route::get('/admin/cities', [App\Http\Controllers\CitiesController::class, 'admin'])->name('cities.admin');

Route::resource('/users', App\Http\Controllers\UsersController::class);

Auth::routes();

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'user_id', 'api_key', 'provider'];

    /**
     * Eloquent relation to user
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Recursive function to print response data
     *
     * @param $array
     * @return array
     */
    function print_array(array $array)
    {
        foreach ($array as $key => $value) {
            if (!is_array($value))
              $array= compact('key','value');
            else {
              $array= $this->print_array($value);
            }
        }
        return $array;
    }
}

app/Http/Controllers/CitiesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller as Controller;
use App\Models\City;
use App\Models\User;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Validator;

class CitiesController extends Controller
{

    /**
     * Show the weather forecasts for the City resources.
     *
     * @return Factory|View
     */
    public function index()
    {
        $user = Auth::user();
        $cities = \App\Models\City::all();
        foreach ($cities as $city) {
            $response = Http::get('http://api.openweathermap.org/data/2.5/weather?q=' . $city->name . '&appid=' . $city->api_key . '&units=metric');
            $data = $response->json();
            if ($response->status() == 200) {
                $city->weather = $data['weather'][0]['description'];
                $city->temp = $data['main']['temp'];
                $city->temp_min = $data['main']['temp_min'];
                $city->temp_max = $data['main']['temp_max'];
                $city->humidity = $data['main']['humidity'];
                $city->feeling = $data['main']['feels_like'];
            }
        }
        return view('cities.forecast', compact('cities', 'user'));
    }

    /**
     * Show the listing of a resource.
     *
     * @return void|View
     */
    public function admin()
    {
        if (Gate::allows('admin-actions')) {
            $cities = \App\Models\City::orderBy('id', 'asc')->paginate(10);
            return view('cities.list', compact('cities'));
        } else return abort(403, 'You are not authorized');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Factory|View|void
     * @throws AuthorizationException
     */
    public function edit($id)
    {
        $city = City::findOrFail($id);
        $users = User::all();
        $this->authorize('update', $city);
        return view('cities.edit', compact('city', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @return false|string
     */
    public function store(Request $request)
    {
        if (Gate::allows('logged-in')) {
            $data = $request->all();
            $rules = [
                'city_name' => 'required|unique:App\Models\City,name',
                'api_token' => 'required|min:2|max:64',
                'provider' => 'nullable',
            ];
            $validator = Validator::make($data, $rules);
            if ($validator->passes()) {
                $response = Http::get('http://api.openweathermap.org/data/2.5/weather?q=' . $request->get('city_name') . '&appid=' . $request->get('api_token') . '&units=metric');
                if ($response->status() === 200) {
                    $city = new City;
                    $city->api_key = $request->get('api_token');
                    $city->name = $request->get('city_name');
                    $city->user_id = Auth::user()->id;
                    if ($provider_exists = $request->get('provider')) $city->provider = $provider_exists;
                    if ($city->save()) {
                        $city->data = $response->json();
                        $response = json_encode($city, true);
                    } else
                        $response = json_encode('Error occured in backend system.');
                } else
                    $response = $response->body();
            } else {
                $response = response()->json($validator->messages(), 200);
            }
        } else $response = abort(403, 'You are not authenticated');
        return $response;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return false|\Illuminate\Http\Client\Response|string
     * @throws AuthorizationException
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $rules = [
            'city_name' => 'required|unique:App\Models\City,name',
            'api_token' => 'required|min:2|max:64',
            'user_id' => 'nullable|int'
        ];
        $validator = Validator::make($data, $rules);
        if ($validator->passes()) {
            $response = Http::get('http://api.openweathermap.org/data/2.5/weather?q=' . $request->get('city_name') . '&appid=' . $request->get('api_token') . '&units=metric');
            if ($response->status() == 200) {
                $city = City::findOrFail($id);
                $this->authorize('update', $city);
                $city->api_key = $request->get('api_token');
                $city->name = $request->get('city_name');
                if ($user_id = $request->get('user_id')) $city->user_id = $user_id;
                if ($city->save()) {
                    $city->data = $response->json();
                    $response = json_encode($city, true);
                } else
                    $response = json_encode('Error occured in backend system.');
            } else
                $response = $response->body();
        } else {
            $response = response()->json($validator->messages(), 200);
        }
        return $response;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     */
    public function destroy($id)
    {
        $city = City::findOrFail($id);
        $this->authorize('update', $city);
        $city->delete();
        return response([], 204);
    }
}

resources/views/cities/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit City '.$city->name)
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card bg-transparent border-0">
                    <div class="card-header bg-transparent border-0">{{ __('Edit City') }}</div>

                    <div class="card-body bg-transparent border-0">
                        <form method="POST" action="{{ route('cities.update', $city->id) }}">
                            @csrf
                            @method('patch')

                            <div class="form-group row">
                                <label for="name"
                                       class="col-md-4 col-form-label text-md-right">{{ __('City name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control @error('name') is-invalid @enderror"
                                           name="name"
                                           value="@if(old($city->city_name)){{old('name')}}@else{{$city->name}}@endif"
                                           autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="api_key"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Api Token') }}</label>

                                <div class="col-md-6">
                                    <input id="api_key" type="text"
                                           class="form-control @error('api_key') is-invalid @enderror"
                                           name="api_key"
                                           value="@if(old($city->api_key)){{old('api_key')}}@else{{$city->api_key}}@endif"
                                           required autocomplete="api_key">

                                    @error('api_key')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="user_id"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Entry owner') }}</label>

                                <div class="col-md-6">
                                    <select id="user_id"
                                            class="form-control selectpicker @error('user_id') is-invalid @enderror"
                                            name="user_id"
                                            required>
                                        <option @if(!$city->user_id)selected @endif value="">
                                            Global (shown for unauthenticated)
                                        </option>
                                        @foreach($users as $user)
                                            <option @if($city->user_id==$user->id)selected @endif value="{{$user->id}}">
                                                {{$user->name}}
                                            </option>
                                        @endforeach
                                    </select>
                                    @error('user_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="button" id="update_city" data-attribute="{{$city->id}}" class="btn btn-primary">
                                        {{ __('Edit City') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cities/list.blade.php
@extends('layouts.app')
@section('title', 'City list')
@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card bg-transparent border-0">
                    <div class="card-header bg-transparent border-0">{{ __('City list') }}</div>
                    <div class="card-body bg-transparent border-0">
                        <table class="table table-striped text-light">
                            <thead>
                            <tr>
                                <th scope="col">
                                    Name
                                </th>
                                <th scope="col">
                                    API Key
                                </th>
                                <th>
                                    Owner
                                </th>
                                <th scope="col">
                                    Actions (View, Delete)
                                </th>
                            </tr>
                            <tr>
                                <th colspan="4">{{$cities->links()}} <a href="{{url('/cities')}}">Create New City</a>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($cities->count()>0)
                            @foreach($cities as $city)
                                <tr id="{{$city->id}}">
                                    <td>
                                        {{$city->name}}
                                    </td>
                                    <td>
                                        {{$city->api_key}}
                                    </td>
                                    <td>
                                        @isset($city->user)   {{$city->user->name}} @else N/a @endisset
                                    </td>
                                    <td class="text-center d-inline-flex mx-auto vertical-center"
                                        style="margin-bottom:1px;position:relative;bottom:1px">
                                        <a style="width:60px;height:auto;" class="btn btn-success  my-2 py-2 mx-1"
                                           href="{{url('/cities/' . $city->id)}}"><i class="fas fa-eye"></i></a>
                                        <a style="width:60px;height:auto;" class="btn btn-warning  my-2 py-2 mx-1"
                                           href="{{url('/cities/' . $city->id.'/edit')}}"><i
                                                class="fas fa-edit"></i></a>
                                        <button data-toggle="confirmation" style="width:60px;height:auto;"
                                                data-attribute="{{$city->id}}"
                                                class="btn btn-danger destroy-city-btn mx-auto my-2 py-2"><i
                                                class="fas fa-times"></i></button>

                                    </td>
                                </tr>
                            @endforeach
                                @else
                            <tr>
                                <td colspan="4">No cities were found, add one!</td>
                                @endif
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection